services:
  - type: web
    name: nexuspath
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: /study-path-api/$1
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /(.*)
        destination: /$1
